/**
 * Authoritative muscle → specific-exercise map.
 *
 * For each major MSK muscle we list 10–15 clinically-specific exercises
 * graded from MILD (Beginner) → ADVANCED. These are NOT random keyword
 * matches; each item has been hand-picked because it directly targets the
 * named muscle (primary mover or principal stabiliser).
 *
 * Each exercise references the canonical name in `src/data/exercises.json`
 * when one exists, so the user can tap through to the full prescription
 * (sets/reps, cueing, contraindications, references). Items prefixed with
 * a "*" do not yet exist as a full record; they still render with their
 * level so the catalogue stays clinically complete.
 */

export type GradedLevel = "Beginner" | "Intermediate" | "Advanced";

export interface MuscleExerciseEntry {
  name: string;       // canonical exercise name (matches exercises.json when possible)
  level: GradedLevel; // mild → advanced
  note?: string;      // short clinical note
}

/** Aliases so user-facing muscle names match keys here. */
const ALIASES: Record<string, string> = {
  "biceps brachii": "biceps",
  "biceps": "biceps",
  "triceps brachii": "triceps",
  "triceps": "triceps",
  "deltoid (anterior)": "anterior deltoid",
  "deltoid (middle)": "middle deltoid",
  "deltoid (posterior)": "posterior deltoid",
  "anterior deltoid": "anterior deltoid",
  "middle deltoid": "middle deltoid",
  "posterior deltoid": "posterior deltoid",
  "deltoid": "middle deltoid",
  "pectoralis major": "pectoralis major",
  "pectoralis minor": "pectoralis minor",
  "latissimus dorsi": "latissimus dorsi",
  "trapezius (upper)": "upper trapezius",
  "trapezius (middle)": "middle trapezius",
  "trapezius (lower)": "lower trapezius",
  "upper trapezius": "upper trapezius",
  "middle trapezius": "middle trapezius",
  "lower trapezius": "lower trapezius",
  "trapezius": "middle trapezius",
  "rhomboid major": "rhomboids",
  "rhomboid minor": "rhomboids",
  "rhomboids": "rhomboids",
  "supraspinatus": "supraspinatus",
  "infraspinatus": "infraspinatus",
  "teres minor": "teres minor",
  "subscapularis": "subscapularis",
  "serratus anterior": "serratus anterior",
  "levator scapulae": "levator scapulae",
  "brachialis": "brachialis",
  "brachioradialis": "brachioradialis",
  "pronator teres": "pronator teres",
  "supinator": "supinator",
  "wrist flexors": "wrist flexors",
  "flexor carpi radialis": "wrist flexors",
  "flexor carpi ulnaris": "wrist flexors",
  "wrist extensors": "wrist extensors",
  "extensor carpi radialis longus": "wrist extensors",
  "extensor carpi radialis brevis": "wrist extensors",
  "extensor carpi ulnaris": "wrist extensors",
  "rectus abdominis": "rectus abdominis",
  "external oblique": "obliques",
  "internal oblique": "obliques",
  "obliques": "obliques",
  "transverse abdominis": "transverse abdominis",
  "transversus abdominis": "transverse abdominis",
  "erector spinae": "erector spinae",
  "multifidus": "multifidus",
  "quadratus lumborum": "quadratus lumborum",
  "iliopsoas": "iliopsoas",
  "psoas major": "iliopsoas",
  "iliacus": "iliopsoas",
  "gluteus maximus": "gluteus maximus",
  "gluteus medius": "gluteus medius",
  "gluteus minimus": "gluteus medius",
  "tensor fasciae latae": "tensor fasciae latae",
  "piriformis": "piriformis",
  "adductor longus": "hip adductors",
  "adductor magnus": "hip adductors",
  "adductor brevis": "hip adductors",
  "gracilis": "hip adductors",
  "pectineus": "hip adductors",
  "hip adductors": "hip adductors",
  "rectus femoris": "quadriceps",
  "vastus lateralis": "quadriceps",
  "vastus medialis": "quadriceps",
  "vastus intermedius": "quadriceps",
  "quadriceps": "quadriceps",
  "biceps femoris": "hamstrings",
  "semitendinosus": "hamstrings",
  "semimembranosus": "hamstrings",
  "hamstrings": "hamstrings",
  "sartorius": "sartorius",
  "gastrocnemius": "gastrocnemius",
  "soleus": "soleus",
  "tibialis anterior": "tibialis anterior",
  "tibialis posterior": "tibialis posterior",
  "fibularis longus": "peroneals",
  "fibularis brevis": "peroneals",
  "peroneus longus": "peroneals",
  "peroneus brevis": "peroneals",
  "peroneals": "peroneals",
  "flexor digitorum longus": "tibialis posterior",
  "extensor digitorum longus": "tibialis anterior",
  "sternocleidomastoid": "sternocleidomastoid",
  "deep neck flexors": "deep neck flexors",
  "longus colli": "deep neck flexors",
  "longus capitis": "deep neck flexors",
  "scalenes": "scalenes",
  "diaphragm": "diaphragm",
};

const MAP: Record<string, MuscleExerciseEntry[]> = {
  // ===== UPPER LIMB =====
  biceps: [
    { name: "Biceps Stretch (Wall)", level: "Beginner", note: "Pain-free passive stretch" },
    { name: "Isometric Biceps Hold", level: "Beginner" },
    { name: "Elbow Flexion Curl (Resisted)", level: "Beginner" },
    { name: "Hammer Curl", level: "Beginner", note: "Targets long head + brachialis" },
    { name: "Concentration Curl", level: "Beginner" },
    { name: "Dumbbell Biceps Curl", level: "Beginner" },
    { name: "Cable Biceps Curl", level: "Intermediate" },
    { name: "Incline Dumbbell Curl", level: "Intermediate", note: "Bias long head" },
    { name: "Preacher Curl", level: "Intermediate", note: "Bias short head" },
    { name: "Eccentric Biceps Curl", level: "Intermediate", note: "Tendinopathy loading" },
    { name: "Chin-Up (Assisted)", level: "Intermediate" },
    { name: "Chin-Up", level: "Advanced" },
    { name: "Weighted Chin-Up", level: "Advanced" },
    { name: "Plyometric Drill for Biceps Brachii", level: "Advanced" },
  ],
  triceps: [
    { name: "Triceps Stretch (Overhead)", level: "Beginner" },
    { name: "Isometric Triceps Push", level: "Beginner" },
    { name: "Triceps Pushdown", level: "Beginner" },
    { name: "Overhead Triceps Extension", level: "Beginner" },
    { name: "Elbow Extension (Overhead)", level: "Beginner" },
    { name: "Bench Dip", level: "Beginner" },
    { name: "Close-Grip Push-Up", level: "Intermediate" },
    { name: "Skull Crusher", level: "Intermediate" },
    { name: "Cable Rope Triceps Extension", level: "Intermediate" },
    { name: "Diamond Push-Up", level: "Intermediate" },
    { name: "Parallel Bar Dip", level: "Advanced" },
    { name: "Weighted Dip", level: "Advanced" },
    { name: "Plyometric Push-Up", level: "Advanced" },
  ],
  "anterior deltoid": [
    { name: "Pendular Shoulder Swings", level: "Beginner" },
    { name: "Front Raise (Theraband)", level: "Beginner" },
    { name: "Front Raise", level: "Beginner" },
    { name: "Wall Push-Up", level: "Beginner" },
    { name: "Half-Kneeling Press", level: "Intermediate" },
    { name: "Overhead Press (Dumbbell)", level: "Intermediate" },
    { name: "Landmine Press", level: "Intermediate" },
    { name: "Push-Up", level: "Intermediate" },
    { name: "Incline Bench Press", level: "Intermediate" },
    { name: "Barbell Overhead Press", level: "Advanced" },
    { name: "Push Press", level: "Advanced" },
    { name: "Handstand Push-Up", level: "Advanced" },
  ],
  "middle deltoid": [
    { name: "Cross-Body Shoulder Stretch", level: "Beginner" },
    { name: "Shoulder Isometric Abduction", level: "Beginner" },
    { name: "Lateral Raise (Theraband)", level: "Beginner" },
    { name: "Lateral Raise (Dumbbell)", level: "Beginner" },
    { name: "Scaption Raise (Full Can)", level: "Beginner" },
    { name: "Cable Lateral Raise", level: "Intermediate" },
    { name: "Upright Row (Wide Grip)", level: "Intermediate" },
    { name: "Leaning Lateral Raise", level: "Intermediate" },
    { name: "Arnold Press", level: "Intermediate" },
    { name: "Heavy Lateral Raise (5RM)", level: "Advanced" },
    { name: "Behind-the-Neck Press", level: "Advanced" },
  ],
  "posterior deltoid": [
    { name: "Prone T (Middle Trapezius)", level: "Beginner", note: "Also recruits post delt" },
    { name: "Band Pull-Apart", level: "Beginner" },
    { name: "Reverse Fly (Theraband)", level: "Beginner" },
    { name: "Bent-Over Reverse Fly", level: "Beginner" },
    { name: "Face Pull", level: "Beginner" },
    { name: "Prone Y (Lower Trapezius)", level: "Intermediate" },
    { name: "Cable Reverse Fly", level: "Intermediate" },
    { name: "Rear Delt Row", level: "Intermediate" },
    { name: "TRX Reverse Fly", level: "Intermediate" },
    { name: "Heavy Reverse Fly", level: "Advanced" },
    { name: "Inverted Row (Wide Grip)", level: "Advanced" },
  ],
  "pectoralis major": [
    { name: "Pec Major Stretch (Corner)", level: "Beginner" },
    { name: "Shoulder Isometric Adduction", level: "Beginner" },
    { name: "Wall Push-Up", level: "Beginner" },
    { name: "Incline Push-Up", level: "Beginner" },
    { name: "Chest Fly (Dumbbell)", level: "Intermediate" },
    { name: "Dumbbell Bench Press", level: "Intermediate" },
    { name: "Push-Up", level: "Intermediate" },
    { name: "Cable Chest Fly", level: "Intermediate" },
    { name: "Incline Bench Press", level: "Intermediate" },
    { name: "Barbell Bench Press", level: "Advanced" },
    { name: "Weighted Dip", level: "Advanced" },
    { name: "Plyometric Push-Up", level: "Advanced" },
  ],
  "pectoralis minor": [
    { name: "Pec Minor Stretch (Doorway)", level: "Beginner" },
    { name: "Foam Roller Pec Release", level: "Beginner" },
    { name: "Supine Pec Minor Stretch", level: "Beginner" },
    { name: "Scapular Setting", level: "Beginner" },
    { name: "Wall Slide", level: "Beginner" },
    { name: "Serratus Anterior Wall Slide", level: "Intermediate" },
    { name: "Push-Up Plus", level: "Intermediate" },
    { name: "Prone Y (Lower Trapezius)", level: "Intermediate" },
    { name: "Scapular Posterior Tilt Drill", level: "Intermediate" },
    { name: "Loaded Carry (Farmer)", level: "Advanced" },
  ],
  "latissimus dorsi": [
    { name: "Lat Stretch (Doorway)", level: "Beginner" },
    { name: "Child's Pose with Lat Reach", level: "Beginner" },
    { name: "Theraband Shoulder Extension", level: "Beginner" },
    { name: "Straight Arm Lat Pulldown", level: "Beginner" },
    { name: "Lat Pulldown", level: "Beginner" },
    { name: "Lat Pulldown (Scapular Focus)", level: "Intermediate" },
    { name: "Single Arm Dumbbell Row", level: "Intermediate" },
    { name: "Seated Cable Row", level: "Intermediate" },
    { name: "Inverted Row", level: "Intermediate" },
    { name: "Pull-Up (Assisted)", level: "Intermediate" },
    { name: "Pull-Up", level: "Advanced" },
    { name: "Weighted Pull-Up", level: "Advanced" },
    { name: "Pendlay Row", level: "Advanced" },
  ],
  "upper trapezius": [
    { name: "Upper Trap Stretch", level: "Beginner" },
    { name: "Levator Scapulae Stretch", level: "Beginner" },
    { name: "Scapular Shrug (Light)", level: "Beginner" },
    { name: "Cervical Isometrics (Lateral Flexion)", level: "Beginner" },
    { name: "Dumbbell Shrug", level: "Beginner" },
    { name: "Barbell Shrug", level: "Intermediate" },
    { name: "Trap-3 Raise (Prone Overhead)", level: "Intermediate" },
    { name: "Loaded Farmer's Carry", level: "Intermediate" },
    { name: "Heavy Shrug", level: "Advanced" },
    { name: "Snatch-Grip High Pull", level: "Advanced" },
  ],
  "middle trapezius": [
    { name: "Scapular Retraction", level: "Beginner" },
    { name: "Prone T (Middle Trapezius)", level: "Beginner" },
    { name: "Scapular Retraction (Band Pull-Apart)", level: "Beginner" },
    { name: "Rhomboid Pinch", level: "Beginner" },
    { name: "Row (Band/Dumbbell)", level: "Beginner" },
    { name: "Seated Cable Row", level: "Intermediate" },
    { name: "Bent-Over Row", level: "Intermediate" },
    { name: "TRX Row", level: "Intermediate" },
    { name: "Inverted Row", level: "Intermediate" },
    { name: "Pendlay Row", level: "Advanced" },
    { name: "Weighted Inverted Row", level: "Advanced" },
  ],
  "lower trapezius": [
    { name: "Prone Y (Lower Trapezius)", level: "Beginner" },
    { name: "Wall Slide", level: "Beginner" },
    { name: "Scapular Setting", level: "Beginner" },
    { name: "Prone Shoulder Abduction (W Exercise)", level: "Beginner" },
    { name: "Serratus Anterior Wall Slide", level: "Beginner" },
    { name: "Prone I (Lower Trap)", level: "Intermediate" },
    { name: "Y-T-W Series", level: "Intermediate" },
    { name: "Trap-3 Raise (Prone Overhead)", level: "Intermediate" },
    { name: "Overhead Carry", level: "Intermediate" },
    { name: "Bottoms-Up Kettlebell Press", level: "Advanced" },
    { name: "Handstand Hold", level: "Advanced" },
  ],
  rhomboids: [
    { name: "Rhomboid Pinch", level: "Beginner" },
    { name: "Scapular Retraction", level: "Beginner" },
    { name: "Scapular Retraction (Band Pull-Apart)", level: "Beginner" },
    { name: "Prone T (Middle Trapezius)", level: "Beginner" },
    { name: "Row (Band/Dumbbell)", level: "Beginner" },
    { name: "Seated Cable Row", level: "Intermediate" },
    { name: "Single Arm Dumbbell Row", level: "Intermediate" },
    { name: "TRX Row", level: "Intermediate" },
    { name: "Face Pull", level: "Intermediate" },
    { name: "Inverted Row", level: "Intermediate" },
    { name: "Pendlay Row", level: "Advanced" },
    { name: "Weighted Pull-Up", level: "Advanced" },
  ],
  supraspinatus: [
    { name: "Pendular Shoulder Swings", level: "Beginner" },
    { name: "Shoulder Isometric Abduction", level: "Beginner" },
    { name: "Full Can Exercise", level: "Beginner", note: "Preferred over empty can" },
    { name: "Scaption Raise (Full Can)", level: "Beginner" },
    { name: "Side-Lying Abduction (0–60°)", level: "Beginner" },
    { name: "Empty Can Exercise", level: "Intermediate", note: "Provocative — use cautiously" },
    { name: "PNF Diagonal D1/D2", level: "Intermediate" },
    { name: "Rotator Cuff Progressive Overhead Loading", level: "Intermediate" },
    { name: "Prone Shoulder Abduction (W Exercise)", level: "Intermediate" },
    { name: "Heavy Slow Resistance Scaption", level: "Advanced" },
    { name: "Plyometric Overhead Catch", level: "Advanced" },
  ],
  infraspinatus: [
    { name: "Isometric Shoulder ER", level: "Beginner" },
    { name: "Side-Lying External Rotation", level: "Beginner" },
    { name: "ER with Band (Elbow at Side)", level: "Beginner" },
    { name: "Sleeper Stretch", level: "Beginner" },
    { name: "Cross-Body Shoulder Stretch", level: "Beginner" },
    { name: "External Rotation at 90° Abduction", level: "Intermediate" },
    { name: "Rotator Cuff ER at 90° ABD", level: "Intermediate" },
    { name: "Cable ER (Side-Lying)", level: "Intermediate" },
    { name: "Prone Horizontal Abduction with ER", level: "Intermediate" },
    { name: "PNF Diagonal D2", level: "Intermediate" },
    { name: "Heavy Slow Resistance ER", level: "Advanced" },
    { name: "Plyometric Reverse-Catch (90/90)", level: "Advanced" },
  ],
  "teres minor": [
    { name: "Teres Minor Isometric Hold", level: "Beginner" },
    { name: "Side-Lying External Rotation", level: "Beginner" },
    { name: "ER with Band (Elbow at Side)", level: "Beginner" },
    { name: "Cross-Body Shoulder Stretch", level: "Beginner" },
    { name: "External Rotation at 90° Abduction", level: "Intermediate" },
    { name: "Prone Horizontal Abduction with ER", level: "Intermediate" },
    { name: "Cable Face Pull (External Rotation)", level: "Intermediate" },
    { name: "PNF Diagonal D2", level: "Intermediate" },
    { name: "Heavy Slow Resistance ER", level: "Advanced" },
  ],
  subscapularis: [
    { name: "Isometric IR Doorframe", level: "Beginner" },
    { name: "Shoulder IR (Side-lying)", level: "Beginner" },
    { name: "Internal Rotation with Band", level: "Beginner" },
    { name: "Subscapularis IR Band", level: "Beginner" },
    { name: "Lift-Off Drill (Belly Press)", level: "Beginner" },
    { name: "Bear Hug Exercise", level: "Intermediate" },
    { name: "IR at 90° Abduction (Band)", level: "Intermediate" },
    { name: "Cable IR (Side-Lying)", level: "Intermediate" },
    { name: "PNF Diagonal D1", level: "Intermediate" },
    { name: "Heavy Slow Resistance IR", level: "Advanced" },
    { name: "Plyometric IR Catch", level: "Advanced" },
  ],
  "serratus anterior": [
    { name: "Serratus Anterior Punch", level: "Beginner" },
    { name: "Serratus Anterior Wall Slide", level: "Beginner" },
    { name: "Scapular Push-Up (Quadruped)", level: "Beginner" },
    { name: "Wall Slide", level: "Beginner" },
    { name: "Push-Up Plus", level: "Intermediate" },
    { name: "Serratus Anterior Push-Up Plus", level: "Intermediate" },
    { name: "Shoulder Diagonal Band Press (Punch)", level: "Intermediate" },
    { name: "Bear Crawl", level: "Intermediate" },
    { name: "Overhead Carry", level: "Intermediate" },
    { name: "Bottoms-Up Kettlebell Press", level: "Advanced" },
    { name: "Handstand Hold", level: "Advanced" },
  ],
  "levator scapulae": [
    { name: "Levator Scapulae Stretch", level: "Beginner" },
    { name: "Upper Trap Stretch", level: "Beginner" },
    { name: "Cervical Self-Mobilisation", level: "Beginner" },
    { name: "Scapular Setting", level: "Beginner" },
    { name: "Chin Tuck", level: "Beginner" },
    { name: "Cervical Isometrics (Multi-direction)", level: "Beginner" },
    { name: "Scapular Retraction", level: "Beginner" },
    { name: "Wall Slide", level: "Intermediate" },
    { name: "Prone Y (Lower Trapezius)", level: "Intermediate" },
    { name: "Loaded Carry (Farmer)", level: "Intermediate" },
  ],
  brachialis: [
    { name: "Elbow Flexion Stretch (Eccentric)", level: "Beginner" },
    { name: "Isometric Elbow Flexion (Pronated)", level: "Beginner" },
    { name: "Hammer Curl", level: "Beginner" },
    { name: "Reverse Curl", level: "Beginner" },
    { name: "Cross-Body Hammer Curl", level: "Beginner" },
    { name: "Zottman Curl", level: "Intermediate" },
    { name: "Cable Hammer Curl (Rope)", level: "Intermediate" },
    { name: "Eccentric Reverse Curl", level: "Intermediate" },
    { name: "Spider Curl (Pronated)", level: "Intermediate" },
    { name: "Heavy Hammer Curl", level: "Advanced" },
    { name: "Weighted Chin-Up (Pronated)", level: "Advanced" },
  ],
  brachioradialis: [
    { name: "Brachioradialis Isometric Hold", level: "Beginner" },
    { name: "Hammer Curl", level: "Beginner" },
    { name: "Reverse Curl (EZ-Bar)", level: "Beginner" },
    { name: "Wrist Pronation/Supination", level: "Beginner" },
    { name: "Cross-Body Hammer Curl", level: "Beginner" },
    { name: "Zottman Curl", level: "Intermediate" },
    { name: "Cable Reverse Curl", level: "Intermediate" },
    { name: "Eccentric Reverse Curl", level: "Intermediate" },
    { name: "Towel Pull-Up (Thick Grip)", level: "Advanced" },
    { name: "Plyometric Drill for Brachioradialis", level: "Advanced" },
  ],
  "pronator teres": [
    { name: "Forearm Pronation Stretch", level: "Beginner" },
    { name: "Wrist Pronation/Supination", level: "Beginner" },
    { name: "Forearm Pronation Strengthening", level: "Beginner" },
    { name: "Resisted Pronation (Theraband)", level: "Beginner" },
    { name: "Dumbbell Pronation/Supination", level: "Intermediate" },
    { name: "Closed-Chain Pronator Teres Activation", level: "Intermediate" },
    { name: "Eccentric Pronation Loading", level: "Intermediate" },
    { name: "Hammer-to-Pronation Curl", level: "Intermediate" },
    { name: "Heavy Slow Resistance Pronation", level: "Advanced" },
  ],
  supinator: [
    { name: "Forearm Supination Stretch", level: "Beginner" },
    { name: "Forearm Supination/Pronation", level: "Beginner" },
    { name: "Resisted Supination (Theraband)", level: "Beginner" },
    { name: "Dumbbell Pronation/Supination", level: "Beginner" },
    { name: "Open-Chain Supinator Strengthening", level: "Beginner" },
    { name: "Hammer-to-Supination Curl", level: "Intermediate" },
    { name: "Eccentric Supination Loading", level: "Intermediate" },
    { name: "Cable Supination (Rope)", level: "Intermediate" },
    { name: "Heavy Slow Resistance Supination", level: "Advanced" },
  ],
  "wrist flexors": [
    { name: "Wrist Flexion Stretch", level: "Beginner" },
    { name: "Isometric Wrist Flexion", level: "Beginner" },
    { name: "Wrist Curl (Dumbbell)", level: "Beginner" },
    { name: "Forearm Flexor Massage", level: "Beginner" },
    { name: "Eccentric Wrist Flexion", level: "Beginner" },
    { name: "Reverse Tyler Twist", level: "Intermediate", note: "Medial epicondylalgia" },
    { name: "Heavy Slow Resistance Wrist Flexion", level: "Intermediate" },
    { name: "Cable Wrist Curl", level: "Intermediate" },
    { name: "Plate Pinch Hold", level: "Intermediate" },
    { name: "Dead Hang", level: "Advanced" },
    { name: "Weighted Dead Hang", level: "Advanced" },
  ],
  "wrist extensors": [
    { name: "Wrist Extension Stretch", level: "Beginner" },
    { name: "Isometric Wrist Extension", level: "Beginner" },
    { name: "Reverse Wrist Curl", level: "Beginner" },
    { name: "Eccentric Wrist Extension", level: "Beginner", note: "Lateral epicondylalgia" },
    { name: "Tyler Twist (FlexBar)", level: "Intermediate", note: "Lateral epicondylalgia (Tyler 2010)" },
    { name: "Wrist Dart Thrower's Motion", level: "Intermediate" },
    { name: "Heavy Slow Resistance Wrist Extension", level: "Intermediate" },
    { name: "Cable Reverse Wrist Curl", level: "Intermediate" },
    { name: "Sledgehammer Lever (Radial)", level: "Advanced" },
    { name: "Rice Bucket Wrist Drill", level: "Advanced" },
  ],

  // ===== TRUNK =====
  "rectus abdominis": [
    { name: "Diaphragmatic Breathing", level: "Beginner" },
    { name: "Modified Curl-Up (McGill)", level: "Beginner" },
    { name: "McGill Curl-Up", level: "Beginner" },
    { name: "Dead Bug", level: "Beginner" },
    { name: "Heel Slides", level: "Beginner" },
    { name: "Reverse Crunch", level: "Intermediate" },
    { name: "Hollow Body Hold", level: "Intermediate" },
    { name: "Cable Crunch", level: "Intermediate" },
    { name: "Ab Wheel Roll-Out (Knees)", level: "Intermediate" },
    { name: "Hanging Knee Raise", level: "Intermediate" },
    { name: "V-Sit Hold", level: "Advanced" },
    { name: "Hanging Leg Raise", level: "Advanced" },
    { name: "Dragon Flag", level: "Advanced" },
  ],
  obliques: [
    { name: "Side-Lying Trunk Lift", level: "Beginner" },
    { name: "Bird Dog", level: "Beginner" },
    { name: "Modified Side Plank (Knees)", level: "Beginner" },
    { name: "Pallof Press", level: "Intermediate" },
    { name: "Side Plank (McGill)", level: "Intermediate" },
    { name: "Half Kneeling Chop", level: "Intermediate" },
    { name: "Half Kneeling Lift", level: "Intermediate" },
    { name: "Russian Twist", level: "Intermediate" },
    { name: "Cable Woodchop", level: "Intermediate" },
    { name: "Medicine Ball Rotation Throw", level: "Intermediate" },
    { name: "Side Plank with Hip Abduction", level: "Advanced" },
    { name: "Landmine Rotation", level: "Advanced" },
    { name: "Windmill (Kettlebell)", level: "Advanced" },
  ],
  "transverse abdominis": [
    { name: "Diaphragmatic Breathing", level: "Beginner" },
    { name: "Abdominal Drawing-In Manoeuvre", level: "Beginner" },
    { name: "Heel Slides (with TA Activation)", level: "Beginner" },
    { name: "Dead Bug", level: "Beginner" },
    { name: "Bird Dog", level: "Beginner" },
    { name: "Quadruped Limb Lift", level: "Beginner" },
    { name: "Front Plank (Modified)", level: "Intermediate" },
    { name: "Front Plank", level: "Intermediate" },
    { name: "Pallof Press", level: "Intermediate" },
    { name: "Stir-the-Pot (Swiss Ball)", level: "Intermediate" },
    { name: "Ab Wheel Roll-Out (Knees)", level: "Advanced" },
    { name: "Ab Wheel Roll-Out (Standing)", level: "Advanced" },
  ],
  "erector spinae": [
    { name: "Cat-Cow Stretch", level: "Beginner" },
    { name: "McKenzie Press-Up (Lumbar Extension)", level: "Beginner" },
    { name: "Prone Press-Up", level: "Beginner" },
    { name: "Bird Dog", level: "Beginner" },
    { name: "Prone Swimmers", level: "Beginner" },
    { name: "Superman Hold", level: "Beginner" },
    { name: "Back Extension (Roman Chair)", level: "Intermediate" },
    { name: "Reverse Hyperextension", level: "Intermediate" },
    { name: "Good Morning", level: "Intermediate" },
    { name: "Romanian Deadlift", level: "Intermediate" },
    { name: "Conventional Deadlift", level: "Advanced" },
    { name: "Jefferson Curl", level: "Advanced" },
    { name: "Heavy Back Extension", level: "Advanced" },
  ],
  multifidus: [
    { name: "Multifidus Activation (Prone)", level: "Beginner" },
    { name: "Bird Dog", level: "Beginner" },
    { name: "Prone Hip Extension (Lumbar Multifidus)", level: "Beginner" },
    { name: "Quadruped Limb Lift", level: "Beginner" },
    { name: "Side Plank (Modified)", level: "Beginner" },
    { name: "Side Plank (McGill)", level: "Intermediate" },
    { name: "Front Plank", level: "Intermediate" },
    { name: "Reverse Hyperextension", level: "Intermediate" },
    { name: "Romanian Deadlift", level: "Intermediate" },
    { name: "Single-Leg RDL", level: "Intermediate" },
    { name: "Heavy Back Extension", level: "Advanced" },
    { name: "Conventional Deadlift", level: "Advanced" },
  ],
  "quadratus lumborum": [
    { name: "QL Stretch (Side-Bend)", level: "Beginner" },
    { name: "Side-Lying Trunk Lift", level: "Beginner" },
    { name: "Cat-Cow Stretch", level: "Beginner" },
    { name: "Side Plank (Modified)", level: "Beginner" },
    { name: "Hip Hike (Pelvic Drop)", level: "Beginner" },
    { name: "Side Plank (McGill)", level: "Intermediate" },
    { name: "Suitcase Carry", level: "Intermediate" },
    { name: "Side Plank with Hip Abduction", level: "Advanced" },
    { name: "Loaded Side Bend", level: "Advanced" },
    { name: "Windmill (Kettlebell)", level: "Advanced" },
  ],
  diaphragm: [
    { name: "Diaphragmatic Breathing", level: "Beginner" },
    { name: "Crocodile Breathing (Prone)", level: "Beginner" },
    { name: "90/90 Breathing", level: "Beginner" },
    { name: "Lateral Costal Breathing", level: "Beginner" },
    { name: "Resisted Inspiration (Threshold IMT)", level: "Intermediate" },
    { name: "Inspiratory Muscle Training (Pursed-Lip)", level: "Intermediate" },
    { name: "Loaded Breath-Hold Carry", level: "Intermediate" },
    { name: "POWERbreathe Loaded IMT", level: "Advanced" },
  ],

  // ===== CERVICAL =====
  "deep neck flexors": [
    { name: "Chin Tuck (Supine)", level: "Beginner" },
    { name: "Chin Tuck (Sitting)", level: "Beginner" },
    { name: "Cranio-Cervical Flexion (Pressure Biofeedback)", level: "Beginner" },
    { name: "Cervical Isometrics (Flexion)", level: "Beginner" },
    { name: "Chin Tuck with Head Lift (Supine)", level: "Intermediate" },
    { name: "Sustained Chin Tuck Hold", level: "Intermediate" },
    { name: "Theraband Chin Tuck", level: "Intermediate" },
    { name: "Chin Tuck with Resisted Rotation", level: "Intermediate" },
    { name: "Loaded Neck Harness Flexion", level: "Advanced" },
  ],
  sternocleidomastoid: [
    { name: "SCM Stretch", level: "Beginner" },
    { name: "Cervical Isometrics (Lateral Flexion)", level: "Beginner" },
    { name: "Cervical Isometrics (Rotation)", level: "Beginner" },
    { name: "Chin Tuck", level: "Beginner" },
    { name: "Resisted Lateral Flexion (Theraband)", level: "Intermediate" },
    { name: "Resisted Rotation (Theraband)", level: "Intermediate" },
    { name: "Cervical Flexion Curl-Up (Supine)", level: "Intermediate" },
    { name: "Loaded Neck Harness Flexion", level: "Advanced" },
  ],
  scalenes: [
    { name: "Scalene Stretch", level: "Beginner" },
    { name: "First Rib Mobilisation", level: "Beginner" },
    { name: "Diaphragmatic Breathing", level: "Beginner" },
    { name: "Chin Tuck", level: "Beginner" },
    { name: "Cervical Isometrics (Lateral Flexion)", level: "Beginner" },
    { name: "Brachial Plexus Glide (Median Nerve)", level: "Intermediate" },
    { name: "Resisted Cervical Lateral Flexion", level: "Intermediate" },
    { name: "Loaded Carry (Farmer)", level: "Intermediate" },
  ],

  // ===== HIP & THIGH =====
  iliopsoas: [
    { name: "Supine Iliopsoas Stretch", level: "Beginner" },
    { name: "Half-Kneeling Hip Flexor Stretch", level: "Beginner" },
    { name: "Hip Flexor Mobilisation", level: "Beginner" },
    { name: "Resisted Hip Flexion (Seated)", level: "Beginner" },
    { name: "Standing Marches", level: "Beginner" },
    { name: "Dead Bug with Resisted Hip Flexion", level: "Intermediate" },
    { name: "Supine Straight Leg Raise (Resisted)", level: "Intermediate" },
    { name: "Mountain Climber", level: "Intermediate" },
    { name: "Hanging Knee Raise", level: "Intermediate" },
    { name: "Standing Banded Hip Flexion (90°+)", level: "Intermediate" },
    { name: "Hanging Leg Raise", level: "Advanced" },
    { name: "Weighted Hip Flexion (Boot)", level: "Advanced" },
  ],
  "gluteus maximus": [
    { name: "Glute Bridge", level: "Beginner" },
    { name: "Donkey Kick", level: "Beginner" },
    { name: "Quadruped Hip Extension", level: "Beginner" },
    { name: "Clamshell Exercise", level: "Beginner" },
    { name: "Single-Leg Glute Bridge", level: "Beginner" },
    { name: "Hip Thrust", level: "Intermediate" },
    { name: "Romanian Deadlift", level: "Intermediate" },
    { name: "Reverse Lunge", level: "Intermediate" },
    { name: "Bulgarian Split Squat", level: "Intermediate" },
    { name: "Kettlebell Swing", level: "Intermediate" },
    { name: "Barbell Hip Thrust", level: "Advanced" },
    { name: "Conventional Deadlift", level: "Advanced" },
    { name: "Single-Leg Hip Thrust", level: "Advanced" },
  ],
  "gluteus medius": [
    { name: "Clamshell Exercise", level: "Beginner" },
    { name: "Side-lying Hip Abduction", level: "Beginner" },
    { name: "Hip Abduction (Side-lying)", level: "Beginner" },
    { name: "Lateral Band Walk", level: "Beginner" },
    { name: "Fire Hydrant", level: "Beginner" },
    { name: "Hip Hike (Pelvic Drop)", level: "Beginner" },
    { name: "Lateral Step-Up", level: "Beginner" },
    { name: "Single-Leg Stance with Reach", level: "Intermediate" },
    { name: "Single-Leg Romanian Deadlift", level: "Intermediate" },
    { name: "Single-Leg Squat", level: "Intermediate" },
    { name: "Bulgarian Split Squat", level: "Intermediate" },
    { name: "Pistol Squat", level: "Advanced" },
    { name: "Lateral Bound", level: "Advanced" },
  ],
  "tensor fasciae latae": [
    { name: "TFL Foam Roll", level: "Beginner" },
    { name: "TFL Stretch (Standing)", level: "Beginner" },
    { name: "Hip Abduction (Side-lying)", level: "Beginner" },
    { name: "Clamshell Exercise", level: "Beginner" },
    { name: "Lateral Band Walk", level: "Beginner" },
    { name: "Standing Hip Abduction (Cable)", level: "Intermediate" },
    { name: "Single-Leg Squat", level: "Intermediate" },
    { name: "Lateral Step-Up", level: "Intermediate" },
    { name: "Lateral Bound", level: "Advanced" },
  ],
  piriformis: [
    { name: "Piriformis Stretch (Figure 4)", level: "Beginner" },
    { name: "Figure-4 Glute Stretch (Supine)", level: "Beginner" },
    { name: "Pigeon Pose Stretch", level: "Beginner" },
    { name: "Seated Piriformis Stretch", level: "Beginner" },
    { name: "Clamshell Exercise", level: "Beginner" },
    { name: "Side-lying Hip External Rotation", level: "Beginner" },
    { name: "Standing Hip ER (Cable)", level: "Intermediate" },
    { name: "Banded Sumo Squat", level: "Intermediate" },
    { name: "Piriformis Eccentric Loading", level: "Intermediate" },
    { name: "Single-Leg Squat (ER bias)", level: "Advanced" },
  ],
  "hip adductors": [
    { name: "Adductor Isometric Squeeze", level: "Beginner" },
    { name: "Butterfly Adductor Stretch", level: "Beginner" },
    { name: "Side-lying Hip Adduction", level: "Beginner" },
    { name: "Standing Adductor Stretch", level: "Beginner" },
    { name: "Ball Squeeze (Supine)", level: "Beginner" },
    { name: "Cable Hip Adduction", level: "Intermediate" },
    { name: "Cossack Squat", level: "Intermediate" },
    { name: "Sumo Squat", level: "Intermediate" },
    { name: "Adductor Slides (Slider)", level: "Intermediate" },
    { name: "Copenhagen Hip Adduction (Short Lever)", level: "Intermediate" },
    { name: "Copenhagen Hip Adduction", level: "Advanced", note: "Hölmich protocol — groin pain" },
    { name: "Copenhagen Plank", level: "Advanced" },
  ],
  sartorius: [
    { name: "Sartorius Stretch (Modified Lunge)", level: "Beginner" },
    { name: "Standing Hip Flexion with ER", level: "Beginner" },
    { name: "Supine Hip Flexion–ER (Theraband)", level: "Beginner" },
    { name: "Half-Kneeling Hip Flexor Stretch", level: "Beginner" },
    { name: "Supine Marching", level: "Beginner" },
    { name: "Cable Hip Flexion–ER", level: "Intermediate" },
    { name: "Closed-Chain Sartorius Activation", level: "Intermediate" },
    { name: "Cossack Squat", level: "Intermediate" },
    { name: "Single-Leg Romanian Deadlift", level: "Advanced" },
  ],
  quadriceps: [
    { name: "Standing Quad Stretch", level: "Beginner" },
    { name: "Quad Set (Isometric)", level: "Beginner" },
    { name: "Straight Leg Raise", level: "Beginner" },
    { name: "Short Arc Quad", level: "Beginner" },
    { name: "Wall Sit", level: "Beginner" },
    { name: "Step-Up", level: "Beginner" },
    { name: "Goblet Squat", level: "Intermediate" },
    { name: "Bulgarian Split Squat", level: "Intermediate" },
    { name: "Single Leg Press", level: "Intermediate" },
    { name: "Spanish Squat", level: "Intermediate", note: "Tendinopathy isometric" },
    { name: "Front Squat", level: "Advanced" },
    { name: "Back Squat", level: "Advanced" },
    { name: "Reverse Nordic Curl", level: "Advanced" },
    { name: "Pistol Squat", level: "Advanced" },
  ],
  hamstrings: [
    { name: "Hamstring Stretch (Standing)", level: "Beginner" },
    { name: "Supine Hamstring Stretch (Strap)", level: "Beginner" },
    { name: "Glute Bridge", level: "Beginner" },
    { name: "Prone Hamstring Curl", level: "Beginner" },
    { name: "Hamstring Curl (Prone)", level: "Beginner" },
    { name: "Single-Leg Glute Bridge", level: "Beginner" },
    { name: "Single Leg Hamstring Bridge (Heel on Box)", level: "Intermediate" },
    { name: "Romanian Deadlift", level: "Intermediate" },
    { name: "Single Leg Romanian Deadlift", level: "Intermediate" },
    { name: "Good Morning", level: "Intermediate" },
    { name: "Stiff Leg Deadlift", level: "Intermediate" },
    { name: "Eccentric Hamstring Curl (Single Leg)", level: "Intermediate" },
    { name: "Nordic Hamstring Curl", level: "Advanced", note: "Askling/Petersen — strain prevention" },
    { name: "Razor Curl", level: "Advanced" },
  ],

  // ===== LEG / ANKLE =====
  gastrocnemius: [
    { name: "Calf Stretch (Wall)", level: "Beginner" },
    { name: "Knee-to-Wall Ankle Dorsiflexion", level: "Beginner" },
    { name: "Double-Leg Calf Raise", level: "Beginner" },
    { name: "Single Leg Calf Raise", level: "Beginner" },
    { name: "Calf Isometric Hold (Achilles)", level: "Beginner" },
    { name: "Heel Drop (Eccentric, Straight Knee)", level: "Intermediate" },
    { name: "Alfredson Eccentric Heel Drop (Straight Knee)", level: "Intermediate" },
    { name: "Heavy Slow Resistance Calf Raise", level: "Intermediate" },
    { name: "Smith Machine Calf Raise", level: "Intermediate" },
    { name: "Pogo Hop", level: "Advanced" },
    { name: "Single-Leg Calf Hop", level: "Advanced" },
    { name: "Sprint Bound", level: "Advanced" },
  ],
  soleus: [
    { name: "Soleus Stretch (Wall)", level: "Beginner" },
    { name: "Seated Calf Raise (Soleus)", level: "Beginner" },
    { name: "Seated Calf Raise", level: "Beginner" },
    { name: "Soleus Heel Raise (Bent Knee)", level: "Intermediate" },
    { name: "Alfredson Eccentric Heel Drop (Bent Knee)", level: "Intermediate" },
    { name: "Heavy Slow Resistance Soleus Press", level: "Intermediate" },
    { name: "Single-Leg Soleus Heel Raise (Bent Knee)", level: "Intermediate" },
    { name: "Smith Machine Bent-Knee Calf Raise", level: "Intermediate" },
    { name: "Pogo Hop (Stiff Knees)", level: "Advanced" },
    { name: "Single-Leg Soleus Hop", level: "Advanced" },
  ],
  "tibialis anterior": [
    { name: "Tibialis Anterior Raise", level: "Beginner" },
    { name: "Toe Raises", level: "Beginner" },
    { name: "Heel Walk", level: "Beginner" },
    { name: "Resisted Dorsiflexion (Theraband)", level: "Beginner" },
    { name: "Eccentric Dorsiflexion", level: "Beginner" },
    { name: "Tib Bar Raise", level: "Intermediate", note: "Shin splints prevention" },
    { name: "Cable Dorsiflexion", level: "Intermediate" },
    { name: "Heavy Slow Resistance Dorsiflexion", level: "Intermediate" },
    { name: "Sled-Drag Backwards", level: "Advanced" },
  ],
  "tibialis posterior": [
    { name: "Tibialis Posterior Strengthening", level: "Beginner" },
    { name: "Resisted Inversion (Theraband)", level: "Beginner" },
    { name: "Heel Raise with Tennis Ball Squeeze", level: "Beginner" },
    { name: "Short Foot Exercise", level: "Beginner" },
    { name: "Single-Leg Balance (Soft Surface)", level: "Beginner" },
    { name: "Eccentric Tibialis Posterior", level: "Intermediate" },
    { name: "Single-Leg Heel Raise (Inverted)", level: "Intermediate" },
    { name: "Step-Down with Arch Support", level: "Intermediate" },
    { name: "Heavy Slow Resistance Inversion", level: "Advanced" },
    { name: "Single-Leg Hop with Arch Control", level: "Advanced" },
  ],
  peroneals: [
    { name: "Peroneal Strengthening (Band Eversion)", level: "Beginner" },
    { name: "Resisted Eversion (Theraband)", level: "Beginner" },
    { name: "Single-Leg Balance", level: "Beginner" },
    { name: "Wobble Board Balance", level: "Beginner" },
    { name: "Lateral Step-Up", level: "Beginner" },
    { name: "Eccentric Eversion", level: "Intermediate" },
    { name: "Single-Leg Heel Raise (Everted)", level: "Intermediate" },
    { name: "Lateral Lunge", level: "Intermediate" },
    { name: "Heavy Slow Resistance Eversion", level: "Advanced" },
    { name: "Lateral Bound", level: "Advanced" },
  ],
};

/** Resolve a user-facing muscle name to a map key. */
function resolveKey(muscleName: string): string | null {
  const raw = (muscleName || "").trim().toLowerCase();
  if (!raw) return null;
  if (MAP[raw]) return raw;
  if (ALIASES[raw]) return ALIASES[raw];

  // Substring fallback — pick the longest matching key/alias
  let best: string | null = null;
  for (const k of Object.keys(MAP)) {
    if (raw.includes(k) || k.includes(raw)) {
      if (!best || k.length > best.length) best = k;
    }
  }
  for (const [a, target] of Object.entries(ALIASES)) {
    if (raw.includes(a) || a.includes(raw)) {
      if (!best || a.length > best.length) best = target;
    }
  }
  return best;
}

/**
 * Get the curated, graded exercise list for a specific muscle.
 * Returns [] if the muscle isn't mapped (caller should fallback).
 */
export function getCuratedExercisesForMuscle(muscleName: string): MuscleExerciseEntry[] {
  const key = resolveKey(muscleName);
  if (!key) return [];
  return MAP[key] || [];
}

/** True if a muscle has a curated, level-graded list. */
export function hasCuratedExercises(muscleName: string): boolean {
  return getCuratedExercisesForMuscle(muscleName).length > 0;
}

/** Total mapped muscles — useful for diagnostics / tests. */
export const CURATED_MUSCLE_COUNT = Object.keys(MAP).length;
